name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: change dir include
      run: cd include
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: change dir common
      run: cd ../common
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: change dir drive
      run: cd ../drivers
    - name: configure
      run: ./configure
    - name: make
      run: make huawei-ups2000
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
